export enum Category {
  PANTS = 'PANTS',
  TOPS = 'TOPS',
  SHIRTS = 'SHIRTS',
  SHOES = 'SHOES',
  DRESSES = 'DRESSES',
  ACCESSORIES = 'ACCESSORIES',
  OUTERWEAR = 'OUTERWEAR',
  UNDERWEAR = 'UNDERWEAR',
  JEWELRY = 'JEWELRY',
  BAGS = 'BAGS'
}
